### ISSUE TITLE
다크테마 지원

### ISSUE THREAD

**Issue by lens0021** [femiwiki/skin#4]
_From @lens0021 on March 22, 2018 17:56_

([주제:Tu342jjjfbhpx8gn](https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Tu342jjjfbhpx8gn)에서 이동하였습니다)

_Copied from original issue: femiwiki/femiwiki.com#108_

**Comment by saschanaz** [comment]
```css
@media (prefers-color-scheme: dark) {
    html {
        scrollbar-color: gray black;
    }
    body {
        background-color: black;
        color: #d9d9d9;
    }
    
    .flow-topic-titlebar {
        background-color: #303030;
    }
    
    .flow-post {
        color: #dddddd;
    }
    
    h1, h2, h3, h4, h5, h6 {
        color: #fff;
    }
    
    #content h1, #content h2, #content h3, #content h4, #content h5, #content h6 {
        color: #d0d0d0;
    }
    
    .oo-ui-textInputWidget input, .oo-ui-textInputWidget textarea {
        background-color: #000;
        color: #fff;
    }
    
    .flow-ui-editorWidget > .flow-ui-editorWidget-editor {
        background-color: #000;
    }
    
    #p-header #p-title-and-tb h1.firstHeading {
        color: #d0d0d0;
    }
    
    .flow-topic-moderatestate-lock .flow-topic-titlebar {
        background-color: #1a1918;
    }
    
    .oo-ui-iconElement-icon, .oo-ui-indicatorElement-indicator {
        filter: invert();
    }
    
    .oo-ui-popupToolGroup.oo-ui-widget-enabled > .oo-ui-popupToolGroup-handle:hover, .oo-ui-barToolGroup-tools.oo-ui-toolGroup-enabled-tools > .oo-ui-tool:not(.oo-ui-toolGroupTool).oo-ui-widget-enabled:hover {
        background-color: #2a2a2a;
    }
    
    .oo-ui-buttonElement-framed.oo-ui-widget-disabled > .oo-ui-buttonElement-button {
        background-color: #3a3732;
        border-color: #3a3732;
    }
    
    .nav-bar #mw-navigation #p-search #searchInput {
        background-color: #000;
        color: #fff;
    }
    
    .suggestions-special {
        background-color: #000;
    }
    
    .suggestions-result-current {
        background-color: #2a4b8d;
    }
    
    .suggestions-special .special-query {
        color: #fff;
    }
}
```

어느정도 보이기만 하도록 만들어봤는데 많이 조정이 필요합니다.
